apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:48:38Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2719"
  uid: dfefb8e2-a2f5-4736-8807-4258b784c775
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.159.126
  clusterIPs:
  - 10.102.159.126
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32543
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
